config/routes.rb
SuMedia::Application.routes.draw do
  root "frames#index"
  resources :frames

  resources :banners

end

app/models/banner.rb
class Banner < ActiveRecord::Base
  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
end

app/models/frame.rb
class Frame < ActiveRecord::Base
  serialize :banner_ids
  after_save :compile

  def banners
    Banner.where(:id => banner_ids)
  end

  def compile
    compiler = FrameCompiler.new(self)
    compiler.compile
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  http_basic_authenticate_with :name => "SergeiUdalov", :password => "lowkick"
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  before_action :set_banner, only: [:show, :edit, :update, :destroy]

  # GET /banners
  # GET /banners.json
  def index
    @banners = Banner.all
  end

  # GET /banners/1
  # GET /banners/1.json
  def show
  end

  # GET /banners/new
  def new
    @banner = Banner.new
  end

  # GET /banners/1/edit
  def edit
  end

  # POST /banners
  # POST /banners.json
  def create
    @banner = Banner.new(banner_params)

    respond_to do |format|
      if @banner.save
        format.html { redirect_to @banner, notice: 'Banner was successfully created.' }
        format.json { render action: 'show', status: :created, location: @banner }
      else
        format.html { render action: 'new' }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banners/1
  # PATCH/PUT /banners/1.json
  def update
    respond_to do |format|
      if @banner.update(banner_params)
        format.html { redirect_to @banner, notice: 'Banner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banners/1
  # DELETE /banners/1.json
  def destroy
    @banner.destroy
    respond_to do |format|
      format.html { redirect_to banners_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banner
      @banner = Banner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def banner_params
      params.require(:banner).permit(:title, :picture, :url)
    end
end

app/controllers/frames_controller.rb
class FramesController < ApplicationController
  before_action :set_frame, only: [:show, :edit, :update, :destroy]

  # GET /frames
  # GET /frames.json
  def index
    @frames = Frame.all
  end

  # GET /frames/1
  # GET /frames/1.json
  def show
  end

  # GET /frames/new
  def new
    @frame = Frame.new
  end

  # GET /frames/1/edit
  def edit
  end

  # POST /frames
  # POST /frames.json
  def create
    @frame = Frame.new(frame_params)

    respond_to do |format|
      if @frame.save
        format.html { redirect_to @frame, notice: 'Frame was successfully created.' }
        format.json { render action: 'show', status: :created, location: @frame }
      else
        format.html { render action: 'new' }
        format.json { render json: @frame.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frames/1
  # PATCH/PUT /frames/1.json
  def update
    respond_to do |format|
      if @frame.update(frame_params)
        format.html { redirect_to @frame, notice: 'Frame was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @frame.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frames/1
  # DELETE /frames/1.json
  def destroy
    @frame.destroy
    respond_to do |format|
      format.html { redirect_to frames_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frame
      @frame = Frame.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def frame_params
      fr_params = params.require(:frame).permit(:title, :width, :height).merge(:banner_ids => params[:frame][:banner_ids])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/frames_helper.rb
module FramesHelper
end

app/views/banners/_form.html.erb
<%= form_for(@banner, :url => url_for(@banner), :html => { :multipart => true }) do |f| %>
  <% if @banner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@banner.errors.count, "error") %> prohibited this banner from being saved:</h2>

      <ul>
      <% @banner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <p>
      <%= image_tag @banner.picture.url(:medium) %>
    </p>
    <%= f.file_field :picture %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/banners/edit.html.erb
<h1>Editing banner</h1>

<%= render 'form' %>

<%= link_to 'Show', @banner %> |
<%= link_to 'Back', banners_path %>

app/views/banners/index.html.erb
<h1>Listing banners</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @banners.each do |banner| %>
      <tr>
        <td><%= banner.title %><br /><%= link_to(image_tag(banner.picture.url(:thumb)), banner.url) %></td>
        <td><%= link_to 'Show', banner %></td>
        <td><%= link_to 'Edit', edit_banner_path(banner) %></td>
        <td><%= link_to 'Destroy', banner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Banner', new_banner_path %>

app/views/banners/new.html.erb
<h1>New banner</h1>

<%= render 'form' %>

<%= link_to 'Back', banners_path %>

app/views/banners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @banner.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= link_to @banner.url, @banner.url %>
</p>
<p>
  <%= image_tag @banner.picture.url %>
</p>

<%= link_to 'Edit', edit_banner_path(@banner) %> |
<%= link_to 'Back', banners_path %>

app/views/frames/_form.html.erb
<%= form_for(@frame) do |f| %>
  <% if @frame.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@frame.errors.count, "error") %> prohibited this frame from being saved:</h2>

      <ul>
      <% @frame.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :width %><br>
    <%= f.number_field :width %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.number_field :height %>
  </div>

  <div>
    <% for banner in Banner.order("updated_at DESC") %>
      <span style="float: left; padding: 20px;">
        <%= check_box_tag "frame[banner_ids][]", banner.id, @frame.banners.include?(banner) %> <%= banner.title %>
        <br /><%= image_tag banner.picture.url(:thumb) %>
      </span>
    <% end %>
  </div>
  <p style="clear: left"></p>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/frames/edit.html.erb
<h1>Editing frame</h1>

<%= render 'form' %>

<%= link_to 'Show', @frame %> |
<%= link_to 'Back', frames_path %>

app/views/frames/index.html.erb
<h1>Listing frames</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @frames.each do |frame| %>
      <tr>
        <td><%= frame.title %> (<%= frame.width %>x<%= frame.height %>)</td>
        <td><%= link_to 'Show', frame %></td>
        <td><%= link_to 'Edit', edit_frame_path(frame) %></td>
        <td><%= link_to 'Destroy', frame, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Frame', new_frame_path %>

app/views/frames/new.html.erb
<h1>New frame</h1>

<%= render 'form' %>

<%= link_to 'Back', frames_path %>

app/views/frames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @frame.title %>
</p>

<p>
  <strong>Width:</strong>
  <%= @frame.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @frame.height %>
</p>

<p><strong>Embded Code:</strong><br />
<textarea rows="5" cols="60">
<!-- SU Media Frame #<%= @frame.id %> "<%= @frame.title %>" <%= @frame.width %>x<%= @frame.height %> -->
<iframe src="//s3.amazonaws.com/su-media-public/frames/frame-<%= @frame.id %>/include.html" frameborder="0" width="<%= @frame.width %>" height="<%= @frame.height %>" scrolling="no"></iframe>

</textarea>
</p>

<p><strong>Example:</strong><br />

<iframe src="//s3.amazonaws.com/su-media-public/frames/frame-<%= @frame.id %>/include.html" frameborder="0" width="<%= @frame.width %>" height="<%= @frame.height %>" scrolling="no"></iframe>
</p>

<%= link_to 'Edit', edit_frame_path(@frame) %> |
<%= link_to 'Back', frames_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuMedia</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to_unless_current "Frames", frames_path %>
| 
<%= link_to_unless_current "Banners", banners_path %>

<%= yield %>

</body>
</html>